### ISSUE TITLE
include arc42.myspreadshop in plausible-monitoring

### ISSUE THREAD

**Issue by gernotstarke** [arc42/arc42.org-site#85]
add this snippet to the shop:

<script defer data-domain="arc42.myspreadshop.de" src="https://plausible.io/js/script.js"></script>

**Comment by Per-Starke** [comment]
I just found out that Spreadshop does not allow custom script-tags, when being placed in the custom html they are automatically removed and there is no other way to place them, so that does not work, sadly. 
But, they offer integration of google analytics. Which is not as privacy-friendly as plausible, but I guess for the Spreadshop-site that doesn't really make a huge difference, they already use a lot of cookies on their own. So Google Analytics is the only way to integrate tracking at all for the shop, shall I do that, or rather not? 

@gernotstarke

**Comment by Per-Starke** [comment]
- [x] ask support for possibility to add custom script tag
- [x] try out GA with my own google account, for testing purposes
- [x] Next days: Check if data is successfully collected

**Comment by Per-Starke** [comment]
@gernotstarke Sadly, the support answered that there is no way to include plausible (at least currently). I've set up Google Analytics from my account, which works fine. If you want access to these analytics, I can give that to you if you tell me your email address used for your google account, or you just have a look at the stats once in a while from my account... What do you prefer?

**Comment by Per-Starke** [comment]
@gernotstarke what do you prefer?

**Comment by gernotstarke** [comment]
you can give me stats from time to time...
